sudo: false
language: python
python:
    "3.5"
env:
  global:
    - secure: "Z6wS6a/YcyT8w5l+2HfMItbn2mbv+f1W43WixoqB4QkgiocjBWvmAQD6PN1sEgWVmZlRvWCABK8FcGG+Y6RPFeNdCE0U1h9hEgOiAnhUpWWH/AhOYDZ0PnFwA3/iRrHS2VFPmhdkjw1BUEfqXaJfDYtlZLgpMMfRvEjIJ8Uqq6M="
    - secure: "JJGGbExBKyXkAltrc4rRLG56ks20/GfGcfugI9mqjeHgQ7IcDvhnouqAIjfbNlhgclyAkWHwJRs7taaM0T9a9AcEQujs2B0JJYOLQSBGnWJSCbsDspWAdlT92U+PzhnZrDm7apg1iBk/c8KtofBo6DqsTveBocFnYXTjeqbSVuY="
    - secure: "TrsYtntXQWgjrXPFaL3aUPoyPtR7pBVqsRx5dIj0yhrPuZR0L2bFi0MOA8cXflaYucx+xa+PEyrPO6FfLl+ri8I2WiXeDLbXlUC614UW6Od1kCklZ7/gk5wor7RwfEtIAtxh5erljUw2N2O9utkRFBDCuASRaQCqBzMItgcUOhA="
    - secure: "CZWsHsATIIAdvAWoHM1niGa8KGfcDR9p49vr/um6DU2wDWt3SVxOei+Z+X8lvIJs4JXiJHzIo6H4qrqf8qxf3hDWjx4TIERz35+5osAWstLkCAxcaWV8JlomxVI+P8tU7dCgZdBeLkVi1O+H8+B2bAVXdK77gcQkSttGh/ykm48="
    - TOX_TESTENV_PASSENV="SF_CONSUMER_KEY SF_CONSUMER_SECRET SF_USER SF_PASSWORD"
cache:
  directories:
    - $HOME/.pip-cache/
before_install:
 - "pip install setuptools_git"
 - "pip install rstcheck"
install:
  - pip install tox
script:
  - rstcheck README.rst
  - echo -e "SF_PK = 'Id'" > salesforce/testrunner/local_settings.py
  - tox -r
