# It is important to set "Limit concurrent jobs" to "1" in repository settings in Travis-CI
language: python
# Ubuntu 22.04 Jammy Jellyfish (has a default Python 3.10, suported 3.7 - 3.10)
dist: jammy
if: branch in (main, travis)
env:
  global:
    - secure: "Z6wS6a/YcyT8w5l+2HfMItbn2mbv+f1W43WixoqB4QkgiocjBWvmAQD6PN1sEgWVmZlRvWCABK8FcGG+Y6RPFeNdCE0U1h9hEgOiAnhUpWWH/AhOYDZ0PnFwA3/iRrHS2VFPmhdkjw1BUEfqXaJfDYtlZLgpMMfRvEjIJ8Uqq6M="
    - secure: "JJGGbExBKyXkAltrc4rRLG56ks20/GfGcfugI9mqjeHgQ7IcDvhnouqAIjfbNlhgclyAkWHwJRs7taaM0T9a9AcEQujs2B0JJYOLQSBGnWJSCbsDspWAdlT92U+PzhnZrDm7apg1iBk/c8KtofBo6DqsTveBocFnYXTjeqbSVuY="
    - secure: "TrsYtntXQWgjrXPFaL3aUPoyPtR7pBVqsRx5dIj0yhrPuZR0L2bFi0MOA8cXflaYucx+xa+PEyrPO6FfLl+ri8I2WiXeDLbXlUC614UW6Od1kCklZ7/gk5wor7RwfEtIAtxh5erljUw2N2O9utkRFBDCuASRaQCqBzMItgcUOhA="
    - secure: "CZWsHsATIIAdvAWoHM1niGa8KGfcDR9p49vr/um6DU2wDWt3SVxOei+Z+X8lvIJs4JXiJHzIo6H4qrqf8qxf3hDWjx4TIERz35+5osAWstLkCAxcaWV8JlomxVI+P8tU7dCgZdBeLkVi1O+H8+B2bAVXdK77gcQkSttGh/ykm48="
    - secure: "hKRKQDaS4H9h1S67nx2znqAEMuDxFynidXa0pzNHqF3N02caUA/TdHPG7Vp78a9TmNoXAC4V2efEg5JfdqUzyrkJzfDX1rWIYSJq37nAroCBQhnNwKbWCGqgfQm6Sb2tXevYhZwqe2Klt7XRx+7c8wavEsrCYLD4m4KjpQ+sekI="
    - TOX_TESTENV_PASSENV="SF_CONSUMER_KEY SF_CONSUMER_SECRET SF_USER SF_PASSWORD SF_HOST"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install tox
script:
  - echo -e "SF_PK = 'Id'" > salesforce/testrunner/local_settings.py
  - tox
jobs:
  include:
    - python: 3.8
      before_install:
        - python3.8 -V
        - python3.10 -V
      env: TOXENV=docs_style,typing,dj41-py310,dj32-py38
    - python: 3.9
      before_install:
        - python3.9 -V
        - pip3.9 install -U setuptools
      env: TOXENV=dj40-py39,dj30-py39,no_django-py39,debug_toolbar-dj32-py39
    - python: 3.7
      before_install:
        - python3.7 -V
      env: TOXENV=dj20-py37,dj22-py37
